[package]
name = "glitzer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive"] }
flate2 = "1.1.5"
hex = "0.4.3"
nom = "8.0.0"
sha1 = "0.10.6"
similar = "2.7.0"
